[package]
name = "gp-leetcode-rust"
version = "0.1.0"
authors = ["George Pickering <@bigpick>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
